
# Primary DB. The single source of truth!
mongodb:
  image: versioneye/mongodb:3.2.6
  container_name: mongodb
  restart: always
  ports:
   - "27017:27017"
  # volumes:
  #  - /mnt/mongodb:/data

# AMQ Message Server
rabbitmq:
  image: reiz/rabbitmq:3.4.2
  container_name: rabbitmq
  restart: always
  ports:
   - "5672:5672"

# Cache
memcached:
  image: reiz/memcached:1.4.14
  container_name: memcached
  restart: always
  ports:
   - "11211:11211"

# Fuzzy search
elasticsearch:
  image: reiz/elasticsearch:0.9.1-1
  container_name: elasticsearch
  restart: always
  ports:
   - "9200:9200"
  # volumes:
  #  - /mnt/elasticsearch:/data
