development:
  # Configure available database sessions. (required)
  clients:
    # Defines the default session. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: veye_dev
      # Provides the hosts the default session can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - <%= ENV['DB_PORT_27017_TCP_ADDR'] ||= 'localhost' %>:<%= ENV['DB_PORT_27017_TCP_PORT'] ||= '27017' %>
      options:
        max_pool_size: 100
  options:
    raise_not_found_error: false
    scope_overwrite_exception: true


test:
  clients:
    default:
      database: veye_test
      hosts:
        - <%= ENV['DB_PORT_27017_TCP_ADDR'] ||= 'localhost' %>:<%= ENV['DB_PORT_27017_TCP_PORT'] ||= '27017' %>
      options:
        max_pool_size: 100
  options:
    raise_not_found_error: false
    scope_overwrite_exception: true


production:
  clients:
    default:
      database: veye_prod
      hosts:
        - <%= ENV['DB_PORT_27017_TCP_ADDR'] ||= 'localhost' %>:<%= ENV['DB_PORT_27017_TCP_PORT'] ||= '27017' %>
        # - <%= ENV['MONGO_RS_2_ADDR'] ||= 'localhost' %>:<%= ENV['MONGO_RS_2_PORT'] ||= '27017' %>
        # - <%= ENV['MONGO_RS_3_ADDR'] ||= 'localhost' %>:<%= ENV['MONGO_RS_3_PORT'] ||= '27017' %>
      options:
        max_pool_size: 100
  options:
    raise_not_found_error: false
    scope_overwrite_exception: true


enterprise:
  # Configure available database clients. (required)
  clients:
    # Defines the default session. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: veye_enterprise
      # Provides the hosts the default session can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - <%= ENV['DB_PORT_27017_TCP_ADDR'] ||= 'localhost' %>:<%= ENV['DB_PORT_27017_TCP_PORT'] ||= '27017' %>
      options:
        max_pool_size: 100
  options:
    raise_not_found_error: false
    scope_overwrite_exception: true
